### ISSUE TITLE
Figure2.

### ISSUE THREAD

**Issue by jw9603** [zhpinkman/CBR#1]
Hello, I found your paper quite fascinating. 
Could I possibly learn about the accuracy of Electra on the LOGIC dataset from Table 2?

**Comment by zhpinkman** [comment]
Hello,
Table 2 has information about the accuracy of Electra, both as a baseline vanilla language model and also with the CBR framework in the second row group of the table. Precision, Recall, and F1 scores are reported here. Let me know if you have any other questions. I'd be happy to help further.

**Comment by jw9603** [comment]
where is Accuracy?
<img width="713" alt="image" src="https://github.com/zhpinkman/CBR/assets/70795645/15124d22-a0cc-45ad-8822-3e2e6e10e847">

**Comment by zhpinkman** [comment]
As the dataset we used had a class imbalance issue, and we care about both the correct answers and incorrect answers in each class, we reported the F1 score, precision, and recall as usual measures to report in these settings. If you want to have an overview of the performances, F1 is the metric you have to focus on here.
Let me know if you have further questions.

**Comment by jw9603** [comment]
To view the results in Table 2, what code do I need to run?

**Comment by zhpinkman** [comment]
You can essentially run the code step by step, as explained in the README. 
First, you have to train the models, and then you can evaluate them and get the results in Table 2. 
The training script is already provided to you in the `job_scripts` directory.
